version: 1
jobs:
  build:
    docker:
      - image: rocker/tidyverse
    steps:
      - checkout
      - run:
          name:  Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - run:
          name:  Build package
          command:  R CMD build .
      - run:
          name: Check package
          command:  R CMD check *tar.gz


